// This is a skeleton starter React component generated by Plasmic.
// Feel free to edit as you see fit.
import * as React from 'react';
import {
  PlasmicMainPage__VariantsArgs,
  PlasmicMainPage,
} from './__internals__/cloudflare_ip_checker/PlasmicMainPage'; // plasmic-import: QZOzF_lZac/render

interface MainPageProps {
  input?: React.ReactNode;
  validationResult?: React.ReactNode;
  // className prop is required for positioning instances of
  // this Component
  className?: string;
  children?: never;
}

function MainPage(props: MainPageProps) {
  return (
    <PlasmicMainPage
      args={{
        input: props.input,
        validationResult: props.validationResult,
      }}
      root={
        // className prop needs to be piped to the root element of this component
        {className: props.className, style: {minHeight: '100vh'}}
      }
    />
  );
}

export default MainPage as React.FunctionComponent<
  React.ComponentProps<typeof MainPage>
>;
